### ISSUE TITLE
Freedman (2008) article in exploration 2

### ISSUE THREAD

**Issue by gustavo-diaz** [bowers-grad-stats-illinois/531-explorations#10]
Exploration 2 mentions a Freedman (2008) article. Sadly, there's two articles from the same author in that year, with seemingly similar topics:

https://arxiv.org/pdf/0808.3914.pdf
http://www.stat.berkeley.edu/~census/neyregcm.pdf

I'm tempted to say the second is the one being mentioned because the first seems to talk mainly about consistency. Still, I just wanted to double check to be safe.

**Comment by drenn2** [comment]
I talked with Professor Bowers -- the comment refers to the first article as the point is about logit models.
