### ISSUE TITLE
Exploration 3 done: Yay for Matrix Algebra!

### ISSUE THREAD

**Issue by jwbowers** [bowers-grad-stats-illinois/531-explorations#13]
@bowers-grad-stats-illinois/531-students  The exploration 3 is done. Enjoy!

**Comment by gustavo-diaz** [comment]
Where can we get the data for news.df? The rmd refers to a local file.

**Comment by drenn2** [comment]
```
read.csv("http://www.jakebowers.org/Data/newsdat.csv")
```

**Comment by gustavo-diaz** [comment]
It is not exactly the same, some variables in lm1 are missing.

`news.df<-read.csv("http://www.jakebowers.org/Data/newsdat.csv")
names(news.df) #city, state, turnout, treat, medianhhinc1000, pastturnout, pair
lm1<-lm(rpre~medhhi1000+medage+blkpct+cands,data=news.df)
#rpre, medage, blkpct, and cands are not in the data
`

**Comment by ychu19** [comment]
Agree with Gus! Would be really helpful if we can get the right dataset for news.df

**Comment by jwbowers** [comment]
Hi all, The .Rmd refers only to a csv file on my website. Are we using different files? This is the one: https://github.com/bowers-grad-stats-illinois/531-explorations/blob/master/exploration3.Rmd .

**Comment by gustavo-diaz** [comment]
The rmd originally says
`news.df<-read.csv("/Users/jwbowers/Documents/PROJECTS/Reg-No-Regrets/data/news.df.csv")`

**Comment by jwbowers** [comment]
Good catch y'all. The file is changed, committed, and pushed. I'm closing this issue with commit b6f67b9 . (Feel to reopen if it doesn't work.)
