### ISSUE TITLE
getting updated 531-explorations repository into rstudio?

### ISSUE THREAD

**Issue by rshakesp** [bowers-grad-stats-illinois/531-explorations#9]
@drenn2 Can we go over how to do this in our workshop Friday? 

Right now, I'm creating a new branch from the 531-explorations folder, then creating a new versioned project in R with that branch every time that there's an exploration update. I feel like there's a more efficient way to do this.

**Comment by drenn2** [comment]
Let's try to get this sorted out before Friday. It'd be good to start on the assignment before then, anyways. I'll be in 410 in a few minutes if people have questions.

**Comment by drenn2** [comment]
To both @bowers-grad-stats-illinois/530-students  and @bowers-grad-stats-illinois/531-students , Rebecca and I discovered that the instructions for rebaseing won't work as they appear [here](https://robots.thoughtbot.com/keeping-a-github-fork-updated) if you don't have an SSH key setup on github. The solution, just use https. To summarize, you'll just be typing the following three lines into the shell:  

```
(For 530)
git remote add upstream https://github.com/bowers-grad-stats-illinois/530-explorations.git  

(For 531)
git remote add upstream https://github.com/bowers-grad-stats-illinois/531-explorations.git  

git fetch upstream  
git rebase upstream/master  
```

Note that you only add the upstream once. In subsequent assignments, you'll just have to fetch and rebase.
